version: "3"

volumes:
  dev-db-data:
  dev-static-data:

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - DEV=true
    image: django-recipe
    container_name: django-recipe
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/recipe/app/
      - dev-static-data:/vol/web/
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    depends_on:
      db:
        condition: service_healthy
    command: /scripts/local/start

  db:
    image: postgres:15-alpine
    container_name: recipe-db
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5