version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - DEV=true
    image: django-recipe
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/recipe/app/
    command: /recipe/start

