"""app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/health-check/', core_views.health_check, name='health-check'),
    # generate schema file(yaml file) for project.
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    # tell what schema we will use when loading swagger docs.
    path(
        'api/docs/',
        SpectacularSwaggerView.as_view(url_name='api-schema'),
        name='api-docs',
    ),
    path(
        'api/user/', include('user.urls')
    ),
    path(
        'api/recipe/', include('recipe.urls')
    ),
]

# This code is used to serve static files (e.g. images, JavaScript, CSS) in
# development mode. Static files are files that don't change often and are not
# generated by Django app. They are usually stored in a separate directory or
# app. If you want to access your static files through the URL you want, you
# will have to use static() method. This method takes 2 arguments: the URL
# prefix for the static files, and the document root where they are stored.
# However, this method is not suitable for production, because it is
# inefficient and insecure. Therefore, you need to check settings.DEBUG.
if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
