#!/bin/sh

set -e

# environment substitute
# basically, it replace environment variable into the value you specify in dockerfile.
envsubst < /etc/nginx/default.conf.tpl > /etc/nginx/conf.d/default.conf
# start nginx in foreground.
nginx -g 'daemon off;'