---
name: Checks # name will be shown on GitHub

on: [push] # trigger, tell GitHub to run action on push

jobs:
  test-lint: # ID
    name: Test and Lint # Name
    runs-on: ubuntu-20.04 # OS that project will run on
    steps:
      - name: Login to Docker Hub # Name of the first step
        uses: docker/login-action@v1 # Use pre-made action provided in GitHub action repo; @v1: version 1
        with:
          username: ${{ secrets.DOCKERHUB_USER }} # Parse into above action
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # This step will be executed if the first one is executed successfully
        uses: actions/checkout@v2
      - name: Test
        run: docker compose -f local.yml run --rm app sh -c "python3 manage.py wait_for_db && python3 manage.py test"
      - name: Lint
        run: docker compose -f local.yml run --rm app sh -c "flake8"

  # Conclusion: the job test-lint will run on ubuntu v20.04 OS, the first step is trying to log in to Docker Hub using
  # secrets set up in GitHub and login docker action v1 (a built-in container). If this step works, it will use checkout
  # action v2 (check if the code is available to perform other next steps). After that, the Test step will be performed
  # using the given command. Finally, the Lint step will be executed. All of this action/step will be executed when
  # performing push action into GitHub