"""
Database models.
"""
# AbstractBaseUser contains functionality for auth system, but not fields,
# PermissionMixin contains functionality for the permissions and fields
# needed.
import uuid
import os

from django.conf import settings
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


# If you want to pass this function to the upload_to argument of the
# ImageField, this function must have exactly 2 parameters: 'instance' and
# 'filename', even if you don't use all of them like the example below.
def recipe_image_file_path(instance, filename):
    """Generate file path for new recipe image."""
    # splitext() will split the pathname into a pair (root, ext) such that
    # root + ext == path, and the extension, ext, is empty or begins with a
    # period and contains at most one period.
    # This will take the extension of the file.
    ext = os.path.splitext(filename)[1]
    # File name will be generated by unique identifier with the extension.
    filename = f'{uuid.uuid4()}{ext}'

    # Return the path.
    return os.path.join('uploads', 'recipe', filename)


class UserManager(BaseUserManager):
    """Manager for users."""

    def create_user(self, email, password=None, **extra_field):
        """Create, save and return a new user."""
        # self.model() is liked User()
        if not email:
            raise ValueError('User must have an email address')

        user = self.model(email=self.normalize_email(email), **extra_field)
        user.set_password(password)
        # support multiple databases.
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None):
        """Create, save and return a new superuser."""
        superuser = self.create_user(email, password)
        superuser.is_staff = True
        superuser.is_superuser = True
        superuser.save(using=self._db)

        return superuser


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system."""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # assign user manager
    objects = UserManager()

    # define field for authentication, default is username, not email.
    USERNAME_FIELD = 'email'


class Recipe(models.Model):
    """Recipe object."""
    title = models.CharField(max_length=255)
    time_minutes = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # blank=True: this field will not be required when the form is submitted.
    description = models.TextField(blank=True)
    # link to the recipe.
    link = models.CharField(max_length=255, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    tags = models.ManyToManyField('Tag')
    ingredients = models.ManyToManyField('Ingredient')
    # The upload_to argument is used to specify the location where the image
    # will be stored, relative to the MEDIA_ROOT setting. You can pass a
    # string or a callable (a function or a class) to the upload_to argument.

    # If you pass a callable, it will receive 2 parameters: the 'instance' and
    # the 'filename' of the uploaded image. The 'instance' is the model
    # instance that the image belongs to, and the 'filename' is the origin
    # name of the uploaded file. You can use these parameters to customize
    # the upload path and file name dynamically, based on some attributes of
    # the model instance or the file.
    image = models.ImageField(null=True, upload_to=recipe_image_file_path)

    def __str__(self):
        return self.title


class Tag(models.Model):
    """Tag for filtering recipes."""
    name = models.CharField(max_length=255)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """Ingredient for recipes."""
    name = models.CharField(max_length=255)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name
